### ISSUE TITLE
USGS - Snotel coordinate system

### ISSUE THREAD

**Issue by jomey** [M3Works/metloom#113]
Question on where the NAD-83 EPSG code information came:
https://github.com/M3Works/metloom/blob/43d578d79a84ed5ec300c83bc66d59067c292d96/metloom/pointdata/usgs.py#L79

I needed a refresher myself today and came across this [in the FAQ](https://www.nrcs.usda.gov/wps/portal/wcc/home/quicklinks/states/colorado/info/program):
```
SNOTEL site coordinates in the WGS84 coordinate system (Latitude/Longitude) are available on our website
```

Comparing the values for 637:ID:SNTL, it looks like that this is also [returned in the SOAP API metadata](https://wcc.sc.egov.usda.gov/awdbWebService/webservice/testwebservice.jsf?webserviceName=/awdbWebService).

So is this conversion necessary?

**Comment by micah-prime** [comment]
Hey Joe! 

I'll need to double check on the USGS source CRS, but that shouldn't effect any of the SNOTEL info. We don't do that conversion for SNOTEL sites
https://github.com/M3Works/metloom/blob/main/metloom/pointdata/snotel.py

**Comment by micah-prime** [comment]
It looks like USGS returns NAD83 values from the metadata endpoint. Here is an example of a metadata response from the API
https://github.com/M3Works/metloom/blob/43d578d79a84ed5ec300c83bc66d59067c292d96/tests/data/usgs_mocks/platoro_meta.txt

**Comment by jomey** [comment]
Ah .. got it. Seems I got twisted around navigating the source code.
Thanks for checking!
