### ISSUE TITLE
CDEC API HTTP 503 Error

### ISSUE THREAD

**Issue by rmower90** [M3Works/metloom#119]
* metloom version: 0.3.9
* Python version: 3.10.12
* Operating System: linux

### Description

I have been using your CDECPointData.points_from_geometry() method to download point data for some time now and recently I ran it and got a 503 error. I know that CDEC has changed their web interface to be more similar to SNOTEL and am wondering if they may have changed their API structure as well? It also may just be down while they are changing their front end? Curious if you are experiencing similar errors trying to access the CDEC APIs?

### What I Did

```
Here is the error:
<img width="760" alt="Screenshot 2024-10-23 at 9 38 42 AM" src="https://github.com/user-attachments/assets/4aeddde9-7c74-456b-82f7-29d800173589">


```

**Comment by rmower90** [comment]
My apologies. The CDEC API seems to be working today. Sorry about that and thanks for your work on metloom!

**Comment by micah-prime** [comment]
@rmower90 thanks for the issue, it is great to hear folks find this useful!
And no worries, these APIs go down from time to time. Let us know if there are any other issue!
