### ISSUE TITLE
Add Soil Moisture to Snotel daily data?

### ISSUE THREAD

**Issue by noahcreany** [M3Works/metloom#86]
https://github.com/M3Works/metloom/blob/ce4fcb4fc0be4133dc4d12767b414ae5a5968bc7/metloom/variables.py#L95

Looks like the soil moisture could be added to this list for stations?

**Comment by micah-prime** [comment]
@noahcreany, yep I think it could be! I'll take a look

**Comment by micah-prime** [comment]
Thanks for the kind words! That is music to my ears. I'll let you know when the changes for this are pushed out into the world.

**Comment by micah-prime** [comment]
This should be ready to roll in version 0.3.7! Let us know if you have any issues.
